# numpy

`numpy` is a Python library for fast computations with vectors and matrices.

It is the basis for many other, more advanced libraries.

In [14]:
import numpy as np

## Vectors

In [15]:
arr = np.array((1,2,3,4))
arr, arr.dtype               # Vector in numpy has a single data-type.

(array([1, 2, 3, 4]), dtype('int32'))

In [16]:
arr = np.array((1, 2, 3, 4.0))
arr, arr.dtype

(array([1., 2., 3., 4.]), dtype('float64'))

In [17]:
arr = np.array((1,2,3,'a'))
arr

array(['1', '2', '3', 'a'], dtype='<U11')

In [20]:
lst = [1,2,3]
lst_lst = lst + [4,5,6]
print(f"list+list: {lst_lst}")
print(f"type(list+list) = {type(lst_lst)}")

arr = np.array((1,2,3))
lst_arr = arr + [4,5,6]
print(f"arr+list: {lst_arr}")
print(f"type(arr+list) = {type(lst_arr)}")

list+list: [1, 2, 3, 4, 5, 6]
type(list+list) = <class 'list'>
arr+list: [5 7 9]
type(arr+list) = <class 'numpy.ndarray'>


In [30]:
arr = np.array((1,2,3))
print(arr/2)
print(arr**2)
print(arr*5)
print(arr + [5])   # the [5] is "broad-cast" to a vector [5,5,5]
try:
    arr + [1,2] #=> ValueError
except ValueError as e:
    print(e)

[0.5 1.  1.5]
[1 4 9]
[ 5 10 15]
[6 7 8]
operands could not be broadcast together with shapes (3,) (2,) 


In [27]:
np.concatenate( (arr, [4], [5,6,7]) )

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
print(np.tanh(arr))
print(np.cos(arr))
print(np.sin(arr))
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))

[0.76159416 0.96402758 0.99505475]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [31]:
arr =  np.array([1,2,3])
arr2 = np.array([4,5,6])

# Many ways to compute a scalar product:
print(np.sum(arr2*arr))
print(arr2.dot(arr))
print(arr2 @ arr)

32
32
32


In [37]:
# Indexing by condition

a = np.array([11,22,33,44,55,66])
print(a%2==0)
print(a[[False,True,False,True,False,True,]])           # Take only the even elements
print(list(a[a%2==0]))           # Take only the even elements

[False  True False  True False  True]
[22 44 66]
[22, 44, 66]


[33, 44]

In [41]:
a = np.array([11,22,33,44,55,66],dtype=np.float64)
print(a)

[11. 22. 33. 44. 55. 66.]


## Matrices

In [46]:
lst = [[1,2,3],[4,5,6]]
arr = np.array(lst)
print(lst)
print(arr)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [33]:
print(arr[0][1])   # Java style
print(arr[0,1])    # C# style

2
2


In [49]:
### : colon operator :

print("First column: ", arr[:,0])
print("Second column: ", arr[:,1])
print("Last column: ", arr[:,-1])
print("First row: ", arr[0,:])
print("Second row: ", arr[1,:])

First column:  [1 4]
Second column:  [2 5]
Last column:  [3 6]
First row:  [1 2 3]
Second row:  [4 5 6]


In [50]:
# Operations along a specific axis:

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))
print(np.sum(arr,axis=-1))
print(sum(arr,axis=0))   # Wrong! you should use np.sum.

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
[ 6 15]


TypeError: 'axis' is an invalid keyword argument for sum()

In [53]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print()
print(np.median(arr))
print()
print(np.median(arr,axis=0))
print()
print(np.median(arr,axis=1))

[[1 2 3]
 [4 5 6]]

3.5

[2.5 3.5 4.5]

[2. 5.]


In [57]:
arr = np.array([[4,2,3],[1,6,5]])
print(arr)
print()
print(np.sort(arr,axis=0))
print()
print(np.sort(arr,axis=1))
print()
np.sort(np.concatenate(arr))

[[4 2 3]
 [1 6 5]]

[[1 2 3]
 [4 6 5]]

[[2 3 4]
 [1 5 6]]


array([1, 2, 3, 4, 5, 6])

In [66]:
# Rounding:

a = np.array([[1./3, 1./7, 1./11],[1./13, 1./17, 1./19]])
print(a)
print(np.round(a,2))
print(np.round(a,3))

[[0.333 0.143 0.091]
 [0.077 0.059 0.053]]
[[0.33 0.14 0.09]
 [0.08 0.06 0.05]]
[[0.333 0.143 0.091]
 [0.077 0.059 0.053]]


In [68]:
np.set_printoptions(precision=3)
print(a)
np.set_printoptions(precision=2)
print(a)

[[0.333 0.143 0.091]
 [0.077 0.059 0.053]]
[[0.33 0.14 0.09]
 [0.08 0.06 0.05]]


In [38]:
# Linear algebra operations

arr = np.array([[1,2],[3,4]])
print("arr Transpose:")
print(arr.T)
print("trace of a:")
print(np.trace(arr))
print("determinant of arr:")
print(np.linalg.det(arr))
print(f"inverse of arr: ")
print(np.linalg.inv(arr))

arr Transpose:
[[1 3]
 [2 4]]
trace of a:
5
determinant of arr:
-2.0000000000000004
inverse of arr: 
[[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
#  Matrix multiplication

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr.dot(arr2))
print(arr @ arr2) # equivalent

[[ 9 12 15]
 [19 26 33]]
[[ 9 12 15]
 [19 26 33]]


In [58]:
# Broad-casting (https://numpy.org/doc/stable/user/basics.broadcasting.html)

observation = np.array([131.0, 188.0])
stations = np.array([[102.0, 203.0],
                  [132.0, 193.0],
                  [45.0, 155.0],
                  [57.0, 173.0]])

# Our goal: find the code that is nearest to observation.

diff = stations - observation    # the broadcast happens here
print(diff)
dist = np.sqrt(np.sum(diff**2, axis=-1))
print(dist)
print(np.min(dist), np.argmin(dist))

# In one line:
np.argmin(np.sqrt(np.sum((stations - observation)**2, axis=-1)))

[[-29.  15.]
 [  1.   5.]
 [-86. -33.]
 [-74. -15.]]
[32.64965543  5.09901951 92.11405973 75.50496672]
5.0990195135927845 1


1

## n-dimensional arrays

In [18]:
picture = np.array([    # a 4-by-4 array of RGB values
     [ [100.0,100,100] , [100,100,100] , [100,100,100] , [100,100,100] ]  ,
     [ [100,100,100] , [100,100,100] , [100,100,100] , [100,100,100] ]  ,
     [ [100,100,100] , [100,100,100] , [100,100,100] , [100,100,100] ]  ,
     [ [100,100,100] , [100,100,100] , [100,100,100] , [100,100,100] ]  ,
])

picture

array([[[100., 100., 100.],
        [100., 100., 100.],
        [100., 100., 100.],
        [100., 100., 100.]],

       [[100., 100., 100.],
        [100., 100., 100.],
        [100., 100., 100.],
        [100., 100., 100.]],

       [[100., 100., 100.],
        [100., 100., 100.],
        [100., 100., 100.],
        [100., 100., 100.]],

       [[100., 100., 100.],
        [100., 100., 100.],
        [100., 100., 100.],
        [100., 100., 100.]]])

In [19]:
picture * [0.5, 1, 1.5]  # Multiply each RGB point elementwise by [0.5, 1, 1.5]

array([[[ 50., 100., 150.],
        [ 50., 100., 150.],
        [ 50., 100., 150.],
        [ 50., 100., 150.]],

       [[ 50., 100., 150.],
        [ 50., 100., 150.],
        [ 50., 100., 150.],
        [ 50., 100., 150.]],

       [[ 50., 100., 150.],
        [ 50., 100., 150.],
        [ 50., 100., 150.],
        [ 50., 100., 150.]],

       [[ 50., 100., 150.],
        [ 50., 100., 150.],
        [ 50., 100., 150.],
        [ 50., 100., 150.]]])

[Broadcasting algorithm](https://numpy.org/doc/stable/user/basics.broadcasting.html):

Compare the dimensions, starting from the rightmost one. Two dimensions are compatible if one of the following holds: 

1. they are equal, or
2. one of them is 1.


In [20]:
picture * [1,2,3,4]

ValueError: operands could not be broadcast together with shapes (4,4,3) (4,) 

## Comparison

In [61]:
# A^(-1)*A == I ?
arr = np.array([[1,2],[3,4]])
arrdotinv = np.linalg.inv(arr).dot(arr)
identity = np.array([[1,0],[0,1]])
print(arrdotinv==identity, "\n")
print( (arrdotinv==identity).all(), "\n" )
print(arrdotinv)
print(arrdotinv[0,0])
print(arrdotinv[1,1])

[[False  True]
 [False  True]] 

False 

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
0.9999999999999998
1.0


In [31]:
print(np.allclose(arrdotinv, identity))

True


In [32]:
print(np.allclose(np.array([[1,0],[0,1]]), np.array([[1.1,0.1],[0.1,1.1]]), rtol=0.01, atol=0.01))
print(np.allclose(np.array([[1,0],[0,1]]), np.array([[1.1,0.1],[0.1,1.1]]), rtol=0.1,  atol=0.1))

False
True


## Solving linear equations

In [42]:
# A child buys ticket for 1.5 shekels. 
# An adult buys ticket for 4 shekels. 
# The total number of people is 2200.
# The total amount collected is 5050 shekels.
# How many children and adults entered the park?
left_hand_side = np.array([
    [1,  1],         #  1*children + 1*adults   = 2200
    [1.5,4]]         #  1.5*children + 4*adults = 5050
)
right_hand_side = np.array(
    [2200,   5050]
)
solution = np.linalg.solve(left_hand_side, right_hand_side)
print(f'children = {solution[0]}, adults = {solution[1]}')

children = 1500.0, adults = 700.0


## Special matrices

In [44]:
print('~~~ 3X4X2 3-dimensional matrix of zeros ~~~')
arr_zeros = np.zeros(shape=(3,4,2))
print(arr_zeros)
print('~~~ 3X4 matrix of ones ~~~')
arr_ones = np.ones((3,4))
print(arr_ones)
print('~~~ 3X4 matrix of tens ~~~')
arr_tens = arr_ones * 10
print(arr_tens)
print('~~~ 3X3 Identity matrix (I) ~~~')
arr_identity = np.eye(3)
print(arr_identity)

~~~ 3X4X2 3-dimensional matrix of zeros ~~~
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
~~~ 3X4 matrix of ones ~~~
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
~~~ 3X4 matrix of tens ~~~
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
~~~ 3X3 Identity matrix (I) ~~~
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
np.linspace(0,20,101)  # returns an array with 101 linearly-spaced numbers between 0 and 20

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8, 20. ])

## Random

In [62]:

print(f'~~~ random: {np.random.random()} ~~~')
print(f'~~~ randint(1,100): {np.random.randint(1,100)} ~~~')
print(f'~~~ randint(1,100 size=(3,3)): ~~~ \n{np.random.randint(1,100, size=(3,3))}')
print(f'~~~ choice([2,3,5,7,11,13],size=(3,3)): ~~~\n{np.random.choice([2,3,5,7,11,13], size=(3,3))}')

~~~ random: 0.2698644872464925 ~~~
~~~ randint(1,100): 95 ~~~
~~~ randint(1,100 size=(3,3)): ~~~ 
[[78 63 50]
 [68 52 14]
 [12 30 84]]
~~~ choice([2,3,5,7,11,13],size=(3,3)): ~~~
[[ 7  5 13]
 [ 2 13 11]
 [ 5 13 13]]


In [47]:
# Normal Distribution:
'''The Normal Distribution is one of the most important distributions.

It is also called the Gaussian Distribution after the German mathematician Carl Friedrich Gauss.

It fits the probability distribution of many events, eg. IQ Scores, Heartbeat etc.

loc - (Mean) where the peak of the bell exists.

scale - (Standard Deviation) how flat the graph distribution should be.

size - The shape of the returned array: '''

normal_dis = np.random.normal(size=(3, 3))
print('~~~ normal distribution: ~~~')
print(normal_dis)
print("loc=0.5, scale=2, size=(3, 3):")
normal_dis = np.random.normal(loc=0.5, scale=2, size=(3, 3))
print(normal_dis)

~~~ normal distribution: ~~~
[[ 0.62683555 -1.60841942 -1.17772129]
 [ 0.8141438   0.00378353  0.22795082]
 [-0.48212608 -0.13272651  0.73517214]]
loc=0.5, scale=2, size=(3, 3):
[[ 1.77896524  0.83128624  1.11399872]
 [-0.5009413  -0.55108854 -0.35952066]
 [ 0.31875574 -0.20833663  0.45354905]]


In [48]:

# Binomial Distribution
'''
Binomial Distribution is a Discrete Distribution.

It describes the outcome of binary scenarios, e.g. toss of a coin, it will either be head or tails.

It has three parameters:

n - number of trials.

p - probability of occurence of each trial (e.g. for toss of a coin 0.5 each).

size - The shape of the returned array.
'''
binomial_dis = np.random.binomial(n=10, p=0.5, size=(3,3))
print('~~~ binomial distribution: ~~~')
print("n=10, p=0.5, size=(3,3):")
print(binomial_dis)

~~~ binomial distribution: ~~~
n=10, p=0.5, size=(3,3):
[[5 6 2]
 [5 5 7]
 [4 7 4]]


In [49]:
# Poisson Distribution
'''
Poisson Distribution is a Discrete Distribution.

It estimates how many times an event can happen in a specified time.
e.g. If someone eats twice a day what is probability he will eat thrice?

It has two parameters:

lam - rate or known number of occurences e.g. 2 for above problem.

size - The shape of the returned array.

'''
poisson_dis = np.random.poisson(lam=2, size=(3,3))
print('~~~ poisson distribution: ~~~')
print("lam=2, size=(3,3):")
print(poisson_dis)

~~~ poisson distribution: ~~~
lam=2, size=(3,3):
[[4 2 1]
 [0 0 2]
 [3 0 1]]


In [22]:

# Uniform Distribution
''' 
Used to describe probability where every event has equal chances of occuring.

E.g. Generation of random numbers.

It has three parameters:

a - lower bound - default 0 .0.

b - upper bound - default 1.0.

size - The shape of the returned array.
'''

uniform_dis = np.random.uniform(size=(3, 3))
print('~~~ uniform distribution: ~~~')
print("size=(3,3):")
print(uniform_dis)


~~~ uniform distribution: ~~~
size=(3,3):
[[0.15534627 0.79926918 0.38372047]
 [0.91058895 0.23816699 0.88687427]
 [0.99572881 0.0218146  0.12049657]]


## Performance test - which array multiplication method is faster?

In [63]:
def list_mult(mat_a,mat_b):
    mat_c = []
    for i in range(len(mat_a)):
        mat_c.append([])
        for j in range(len(mat_b[0])):
            mat_c[i].append(sum([mat_a[i][k]*mat_b[k][j] for k in range(len(mat_b))]))
    return mat_c

def array_mult(mat_a,mat_b):
    return mat_a @ mat_b

In [64]:
mat_a = np.random.randint(-100,100,size=(3,3))
mat_b = np.random.randint(-100,100,size=(3,3))

lst_a = list(mat_a)
lst_b = list(mat_b)

print(list_mult(lst_a,lst_b))
print(array_mult(mat_a,mat_b))

[[-8950, 4195, -105], [8648, -2967, -1380], [7424, -3896, 140]]
[[-8950  4195  -105]
 [ 8648 -2967 -1380]
 [ 7424 -3896   140]]


In [65]:

from time import perf_counter   # Exact measurement of CPU time
def measure_time(func, *args, **kwargs):
    """ return the run-time of the given function, in fractional seconds. """
    start = perf_counter()
    result = func(*args, **kwargs)
    end = perf_counter()
    return end-start

In [66]:
mat_a = np.random.randint(-100,100,size=(200,200))
mat_b = np.random.randint(-100,100,size=(200,200))

lst_a = list(mat_a)
lst_b = list(mat_b)

print(f"list_mult: {measure_time(list_mult, lst_a,lst_b)} seconds")
print(f"array_mult: {measure_time(array_mult, mat_a,mat_b)} seconds")
print("So what is faster?")

list_mult: 1.2259513999742921 seconds
array_mult: 0.011019099998520687 seconds
So what is faster?
