In [1]:
import numpy as np

## Vectors

In [2]:
arr = np.array((1,2,3,4.0))
arr

array([1., 2., 3., 4.])

In [10]:
arr = np.array((1,2,3,'a'))
arr

array(['1', '2', '3', 'a'], dtype='<U11')

In [3]:
lis = [1,2,3]
print(f"list+list: {lis+[4,5,6]}")

arr = np.array((1,2,3))
lst_arr = arr + [4,5,6]
print(f"arr + list: {lst_arr}")
print(f"type(arr + list) = {type(lst_arr)}")

list+list: [1, 2, 3, 4, 5, 6]
arr + list: [5 7 9]
type(arr + list) = <class 'numpy.ndarray'>


In [12]:
print(arr/2)
print(arr**2)
print(arr*5)
print(arr + [5])
try:
    arr + [1,2] #=> ValueError
except ValueError as e:
    print(e)

[0.5 1.  1.5]
[1 4 9]
[ 5 10 15]
[6 7 8]
operands could not be broadcast together with shapes (3,) (2,) 


In [13]:
print(np.tanh(arr))
print(np.cos(arr))
print(np.sin(arr))
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))

[0.76159416 0.96402758 0.99505475]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [14]:
arr =  np.array([1,2,3])
arr2 = np.array([4,5,6])

# Many ways to compute a scalar product:
print(np.sum(arr2*arr))
print(arr2.dot(arr))
print(arr2 @ arr)

32
32
32


## Matrices

In [15]:
arr = np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [16]:
print(arr[0][1])   # Java style
print(arr[0,1])    # C# style

2
2


In [17]:
print("First column: ", arr[:,0])
print("Second column: ", arr[:,1])
print("First row: ", arr[0,:])
print("Second row: ", arr[1,:])

First column:  [1 3]
Second column:  [2 4]
First row:  [1 2]
Second row:  [3 4]


In [18]:
print("arr Transpose:")
print(arr.T)
print("trace of a:")
print(np.trace(arr))
print("determinant of arr:")
print(np.linalg.det(arr))
print(f"inverse of arr: ")
print(np.linalg.inv(arr))

arr Transpose:
[[1 3]
 [2 4]]
trace of a:
5
determinant of arr:
-2.0000000000000004
inverse of arr: 
[[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr.dot(arr2))
print(arr @ arr2) # equivalent

[[ 9 12 15]
 [19 26 33]]
[[ 9 12 15]
 [19 26 33]]


## Comparison

In [22]:
# a^(-1)*a == I ?
print(np.linalg.inv(arr).dot(arr) == np.array([[1,0],[0,1]]))
print(np.linalg.inv(arr).dot(arr))

[[False  True]
 [False  True]]
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


In [15]:
np.allclose(np.linalg.inv(arr).dot(arr), np.array([[1,0],[0,1]]))

True

In [25]:
print(np.allclose(np.array([[1,0],[0,1]]), np.array([[1.1,0.1],[0.1,1.1]]), rtol=0.01, atol=0.01))
print(np.allclose(np.array([[1,0],[0,1]]), np.array([[1.1,0.1],[0.1,1.1]]), rtol=0.1, atol=0.1))

False
True


## Solving linear equations

In [16]:
# A child buys ticket for 1.5 shekels. 
# An adult buys ticket for 4 shekels. 
# The total number of people is 2200.
# The total amount collected is 5050 shekels.
# How many children and adults entered the park?
left_hand_side = np.array([
    [1,1],           #  1*children + 1*adults = 2200
    [1.5,4]]         #  1.5*children + 4*adults = 5050
)
right_hand_side = np.array(
    [2200,        
    5050]          
)
solution = np.linalg.solve(left_hand_side, right_hand_side)
print(f'children = {solution[0]}, adults = {solution[1]}')

children = 1500.0, adults = 700.0


## Special matrices

In [27]:
print('~~~ 3X4X2 3-dimensional matrix of zeros ~~~')
arr_zeros = np.zeros((3,4,2))
print(arr_zeros)
print('~~~ 3X4 matrix of ones ~~~')
arr_ones = np.ones((3,4))
print(arr_ones)
print('~~~ 3X4 matrix of tens ~~~')
arr_tens = arr_ones * 10
print(arr_tens)
print('~~~ 3X3 Identity matrix (I) ~~~')
arr_identity = np.eye(3)
print(arr_identity)

~~~ 3X4X2 3-dimensional matrix of zeros ~~~
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
~~~ 3X4 matrix of ones ~~~
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
~~~ 3X4 matrix of tens ~~~
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
~~~ 3X3 Identity matrix (I) ~~~
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
np.linspace(0,20,101)  # returns an array with 101 linearly-spaced numbers between 0 and 20

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8, 20. ])

## Random

In [4]:

print(f'~~~ random: {np.random.random()} ~~~')
print(f'~~~ randint(1,100): {np.random.randint(1,100)} ~~~')
print(f'~~~ randint(1,100 size=(3,3)): ~~~ \n{np.random.randint(1,100, size=(3,3,3))}')
print(f'~~~ choice = [2,3,5,7,11,13],size=(3,3) ~~~\n{np.random.choice([2,3,5,7,11,13], size=(3,3))}')

~~~ random: 0.9569232114743179 ~~~
~~~ randint(1,100): 62 ~~~
~~~ randint(1,100 size=(3,3)): ~~~ 
[[[12 46 24]
  [99 75 34]
  [15 99 32]]

 [[45 68 88]
  [67 16 70]
  [75  4 12]]

 [[14 15 56]
  [82 41  4]
  [96 79 48]]]
~~~ choice = [2,3,5,7,11,13],size=(3,3) ~~~
[[ 5  5  5]
 [ 5 13  5]
 [ 5  3 13]]


In [19]:
# Normal Distribution:
'''The Normal Distribution is one of the most important distributions.

It is also called the Gaussian Distribution after the German mathematician Carl Friedrich Gauss.

It fits the probability distribution of many events, eg. IQ Scores, Heartbeat etc.

loc - (Mean) where the peak of the bell exists.

scale - (Standard Deviation) how flat the graph distribution should be.

size - The shape of the returned array: '''

normal_dis = np.random.normal(size=(3, 3))
print('~~~ normal distribution: ~~~')
print(normal_dis)
print("loc=0.5, scale=2, size=(3, 3):")
normal_dis = np.random.normal(loc=0.5, scale=2, size=(3, 3))
print(normal_dis)

~~~ normal distribution: ~~~
[[ 0.50967727  0.39858778 -1.09028441]
 [ 1.61470804  2.00672151  0.49025323]
 [-0.14599353 -0.72982048 -0.24806031]]
loc=0.5, scale=2, size=(3, 3):
[[-1.60944596 -1.37152222  0.20230573]
 [-1.80345376  2.65796812  2.32961083]
 [ 2.10872108 -0.52245198  4.84574201]]


In [20]:

# Binomial Distribution
'''
Binomial Distribution is a Discrete Distribution.

It describes the outcome of binary scenarios, e.g. toss of a coin, it will either be head or tails.

It has three parameters:

n - number of trials.

p - probability of occurence of each trial (e.g. for toss of a coin 0.5 each).

size - The shape of the returned array.
'''
binomial_dis = np.random.binomial(n=10, p=0.5, size=(3,3))
print('~~~ binomial distribution: ~~~')
print("n=10, p=0.5, size=(3,3):")
print(binomial_dis)

~~~ binomial distribution: ~~~
n=10, p=0.5, size=(3,3):
[[5 5 5]
 [6 5 5]
 [3 4 3]]


In [21]:
# Poisson Distribution
'''
Poisson Distribution is a Discrete Distribution.

It estimates how many times an event can happen in a specified time.
e.g. If someone eats twice a day what is probability he will eat thrice?

It has two parameters:

lam - rate or known number of occurences e.g. 2 for above problem.

size - The shape of the returned array.

'''
poisson_dis = np.random.poisson(lam=2, size=(3,3))
print('~~~ poisson distribution: ~~~')
print("lam=2, size=(3,3):")
print(poisson_dis)

~~~ poisson distribution: ~~~
lam=2, size=(3,3):
[[1 1 4]
 [2 2 1]
 [2 1 3]]


In [22]:

# Uniform Distribution
''' 
Used to describe probability where every event has equal chances of occuring.

E.g. Generation of random numbers.

It has three parameters:

a - lower bound - default 0 .0.

b - upper bound - default 1.0.

size - The shape of the returned array.
'''

uniform_dis = np.random.uniform(size=(3, 3))
print('~~~ uniform distribution: ~~~')
print("size=(3,3):")
print(uniform_dis)


~~~ uniform distribution: ~~~
size=(3,3):
[[0.15534627 0.79926918 0.38372047]
 [0.91058895 0.23816699 0.88687427]
 [0.99572881 0.0218146  0.12049657]]


## Performance test - which array multiplication method is faster?

In [5]:
def my_timer(orig_func):
    import time
    def wrapper(*args, **kwargs):
        t1 = time.time()
        result = orig_func(*args, **kwargs)
        t2 = time.time() - t1
        print(f'{ orig_func.__name__} ran in: {t2} sec')
        return result
    return wrapper


In [6]:
@my_timer
def list_mult(mat_a,mat_b):
    mat_c = []
    for i in range(len(mat_a)):
        mat_c.append([])
        for j in range(len(mat_b[0])):
            sum_val = 0
            for k in range(len(mat_b)):
                sum_val+= mat_a[i][k]*mat_b[k][j]
            mat_c[i].append(sum_val)
    return mat_c


@my_timer           
def array_mult(mat_a,mat_b):
    return mat_a @ mat_b

In [7]:
mat_a = np.random.randint(-100,100,size=(3,3))
mat_b = np.random.randint(-100,100,size=(3,3))

lst_a = list(mat_a)
lst_b = list(mat_b)

print(list_mult(lst_a,lst_b))
print(array_mult(mat_a,mat_b))

list_mult ran in: 0.0 sec
[[-1130, 6315, -8708], [-3172, 4986, -2192], [1022, 304, -2978]]
array_mult ran in: 0.06382369995117188 sec
[[-1130  6315 -8708]
 [-3172  4986 -2192]
 [ 1022   304 -2978]]


In [8]:
mat_a = np.random.randint(-100,100,size=(200,200))
mat_b = np.random.randint(-100,100,size=(200,200))

lst_a = list(mat_a)
lst_b = list(mat_b)
list_mult(lst_a,lst_b)
array_mult(mat_a,mat_b)
print("So what is faster?")

list_mult ran in: 2.3010833263397217 sec
array_mult ran in: 0.009976863861083984 sec
So what is faster?
